import { normalizeDisplayLanguage } from './displayNames.js';

const UI_TEXT = {
    en: {
        activeTimeRange: 'Active Time Range',
        activeWindow: 'Active Window',
        add: 'Add',
        allDay: 'All day',
        allUpgradesComplete: 'All upgrades complete',
        appliedStrategy: 'Strategy',
        builder: 'Builder',
        builderBoost: 'Builder Boost',
        chooseBuilderPriority: 'Choose how builders are prioritized.',
        completed: 'Completed',
        cwlSafe: 'CWL Safe',
        cwlSafeHelp:
            'Protect selected heroes during the monthly CWL safe window from day 2 00:00 to day 12 00:00.',
        displayLanguage: 'Display Language',
        clear: 'Clear',
        cannotFormat: 'Cannot format',
        duration: 'Duration',
        done: 'done',
        dynamicPriority: 'Dynamic priority',
        enableTimeWindow: 'Enable Time Window',
        end: 'End',
        endTime: 'End Time',
        fixedPriority: 'Fixed Priority',
        fixedPriorityMap: 'Fixed priority map',
        formatJson: 'Format JSON',
        generateSchedule: 'Generate Schedule',
        heroAwake: 'Hero Awake',
        heroAwakeHelp: 'Pick a time, then choose which heroes must be awake.',
        heroAwakeTime: 'Hero Awake Time',
        heroes: 'Heroes',
        iterations: 'iterations',
        jsonInputLabel: 'Paste village JSON data',
        invalidJson: 'Invalid JSON',
        level: 'Level',
        mappingCoverage: 'mapping coverage',
        markDone: 'Mark Done',
        makespan: 'Makespan',
        mustBeAwakeAt: 'Must Be Awake At',
        noHeroAwakeRules: 'No hero awake rules yet.',
        none: 'None',
        optimizationScore: 'Optimization Score',
        optimizationStrategy: 'Optimization Strategy',
        priorityMode: 'Priority Mode',
        progress: 'Progress',
        protectedHeroes: 'Protected Heroes',
        protectedHeroesCount: (count) =>
            `${count} protected hero${count > 1 ? 'es' : ''}`,
        remaining: 'Remaining',
        remove: 'Remove',
        resetProgress: 'Reset Progress',
        resetSettings: 'Reset Settings',
        resetProgressConfirm:
            'Reset progress for the current player and strategy?',
        resetSettingsConfirm:
            'Reset schedule settings and active-time preferences? Progress will be kept.',
        resourceReductionHelp:
            'Applies a reduction to builder durations in 5% increments.',
        rerunToRefresh: 'Settings changed - rerun to refresh',
        scheduleGenerator: 'Schedule Generator',
        start: 'Start',
        startTime: 'Start Time',
        taskCategories: {
            Defense: 'Defense',
            Resource: 'Resource',
            Offense: 'Offense',
            Hero: 'Hero',
        },
        strategyDescriptions: {
            LPT: 'Keeps builders busy with the longest upgrades first.',
            SPT: 'Clears quick wins to reveal long blockers sooner.',
            Balanced:
                'Balances upgrade duration, resource use, hero availability, and category spread.',
            ResourceSmoothing:
                'Smooths resource pressure so one resource type is less likely to bottleneck the plan.',
            CWLSafe:
                'Protects selected heroes during the monthly CWL safe window and prioritizes them outside it.',
        },
        strategyLabels: {
            LPT: 'Longest Processing Time (Legacy)',
            SPT: 'Shortest Processing Time (Legacy)',
            Balanced: 'Balanced',
            ResourceSmoothing: 'Resource Smoothing',
            CWLSafe: 'CWL Safe',
        },
        tasks: 'Tasks',
        timeLeft: 'Time Left',
        timelineCards: 'Timeline Cards',
        timelineChart: 'Timeline Chart',
        tipZoom: 'Tip: Pinch or Ctrl + Mouse Wheel to zoom',
        undoResetProgress: 'Undo Reset Progress',
        unmapped: 'unmapped',
        useSavedPriority: 'Use saved priority map ordering.',
        validationSummary: 'Validation Summary',
        validJson: 'Valid JSON',
        ruleCount: (count) => `${count} rule${count > 1 ? 's' : ''}`,
    },
    zh: {
        activeTimeRange: '活跃时间段',
        activeWindow: '活跃窗口',
        add: '添加',
        allDay: '全天',
        allUpgradesComplete: '所有升级已完成',
        appliedStrategy: '策略',
        builder: '工人',
        builderBoost: '工人加速',
        chooseBuilderPriority: '选择工人的升级排程优先级。',
        completed: '已完成',
        cwlSafe: 'CWL 安全',
        cwlSafeHelp:
            '保护选中的英雄，使其避开每月 2 号 00:00 到 12 号 00:00 的 CWL 安全窗。',
        displayLanguage: '显示语言',
        clear: '清空',
        cannotFormat: '无法格式化',
        duration: '耗时',
        done: '已完成',
        dynamicPriority: '动态优先级',
        enableTimeWindow: '启用时间窗口',
        end: '结束',
        endTime: '结束时间',
        fixedPriority: '固定优先级',
        fixedPriorityMap: '固定优先级表',
        formatJson: '格式化 JSON',
        generateSchedule: '生成计划',
        heroAwake: '英雄醒着',
        heroAwakeHelp: '先选一个时间点，再选择必须醒着的英雄。',
        heroAwakeTime: '英雄必须醒着',
        heroes: '英雄',
        iterations: '轮迭代',
        jsonInputLabel: '粘贴村庄 JSON 数据',
        invalidJson: 'JSON 无效',
        level: '等级',
        mappingCoverage: '映射覆盖率',
        markDone: '标记完成',
        makespan: '总工期',
        mustBeAwakeAt: '必须醒着的时间',
        noHeroAwakeRules: '还没有英雄醒着规则。',
        none: '无',
        optimizationScore: '优化评分',
        optimizationStrategy: '优化策略',
        priorityMode: '优先级模式',
        progress: '进度',
        protectedHeroes: '受保护英雄',
        protectedHeroesCount: (count) => `${count} 个受保护英雄`,
        remaining: '剩余',
        remove: '删除',
        resetProgress: '重置进度',
        resetSettings: '重置设置',
        resetProgressConfirm: '要重置当前玩家和策略的完成进度吗？',
        resetSettingsConfirm: '要重置排程设置和活跃时间偏好吗？进度会保留。',
        resourceReductionHelp: '按 5% 间隔缩短工人升级耗时。',
        rerunToRefresh: '设置已更改，请重新生成',
        scheduleGenerator: '计划生成器',
        start: '开始',
        startTime: '开始时间',
        taskCategories: {
            Defense: '防御',
            Resource: '资源',
            Offense: '进攻',
            Hero: '英雄',
        },
        strategyDescriptions: {
            LPT: '优先安排耗时最长的升级，让工人尽量持续做大项目。',
            SPT: '优先清理耗时最短的升级，更快完成一批小项目。',
            Balanced: '综合考虑耗时、资源压力、英雄可用性和类别分布。',
            ResourceSmoothing: '平滑资源消耗，减少某一种资源长期卡住排程。',
            CWLSafe:
                '保护选中的英雄避开每月 CWL 安全窗，并在窗外优先安排英雄升级。',
        },
        strategyLabels: {
            LPT: '长任务优先',
            SPT: '短任务优先',
            Balanced: '均衡',
            ResourceSmoothing: '资源平滑',
            CWLSafe: 'CWL 安全',
        },
        tasks: '任务',
        timeLeft: '剩余时间',
        timelineCards: '时间线卡片',
        timelineChart: '时间线图',
        tipZoom: '提示：双指缩放，或按住 Ctrl 并滚动鼠标缩放',
        undoResetProgress: '撤销重置进度',
        unmapped: '未映射',
        useSavedPriority: '使用保存的优先级顺序。',
        validationSummary: '校验摘要',
        validJson: 'JSON 有效',
        ruleCount: (count) => `${count} 条规则`,
    },
};

export function getUiText(language = 'zh') {
    return UI_TEXT[normalizeDisplayLanguage(language)] || UI_TEXT.zh;
}

export function getCategoryLabel(category, language = 'zh') {
    const text = getUiText(language);
    return text.taskCategories?.[category] || category;
}
